//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Turpax.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Turpax
    {
        public int Id { get; set; }
        [Display(Name = "Satýþ Tarihi")]
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> Tarih_Saat { get; set; }
        public string Satis_tipi { get; set; }
        public string Filo_kodu { get; set; }
        public string Pompaci { get; set; }
        public string Plaka { get; set; }
        public string Pompa { get; set; }
        public string Urun_adi { get; set; }
        public Nullable<decimal> Istasyon_fiyati { get; set; }
        public Nullable<decimal> Satis_fiyati { get; set; }
        public Nullable<decimal> Litre { get; set; }
        public Nullable<decimal> Tutar { get; set; }
    }
}
